#!/usr/bin/env bun
/**
 * One-shot codegen: parse the externally-generated ANSI art in
 * `new-logo.js` (root) and emit `src/render/chrome/logo-data.ts` as a
 * structured array of `{ ch, rgb }` cells per row. The wordmark renderer
 * consumes this data to colour each block character individually so the
 * cyan gradient survives the trip to terminal.
 *
 * Re-run when the source JS regenerates:
 *   bun run dev/gen-logo-data.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const SRC = join(ROOT, "new-logo.js");
const OUT = join(ROOT, "src/render/chrome/logo-data.ts");

type Cell = { ch: string; rgb: [number, number, number] | null };

// biome-ignore lint/suspicious/noControlCharactersInRegex: parses ANSI ESC sequences from txtimg output.
const CELL_RE = /\u001b\[38;2;(\d+);(\d+);(\d+)m([^\u001b]+)\u001b\[0m/g;

function parseLine(line: string): Cell[] {
  const cells: Cell[] = [];
  let lastIdx = 0;
  CELL_RE.lastIndex = 0;
  let m: RegExpExecArray | null;
  // biome-ignore lint/suspicious/noAssignInExpressions: standard regex iteration.
  while ((m = CELL_RE.exec(line)) !== null) {
    // Plain (uncoloured) chars between colour escapes.
    for (let i = lastIdx; i < m.index; i++) {
      const ch = line[i] ?? "";
      if (ch !== "") cells.push({ ch, rgb: null });
    }
    // The captured group may hold multiple characters when chars share a
    // colour run. Split into one cell per char so the colour map indexes
    // cell-by-cell.
    const ch = m[4] ?? "";
    const rgb: [number, number, number] = [Number(m[1]), Number(m[2]), Number(m[3])];
    for (const c of [...ch]) cells.push({ ch: c, rgb });
    lastIdx = CELL_RE.lastIndex;
  }
  for (let i = lastIdx; i < line.length; i++) {
    const ch = line[i] ?? "";
    if (ch !== "") cells.push({ ch, rgb: null });
  }
  return cells;
}

function extractArray(source: string): string[] {
  const start = source.indexOf("[");
  const end = source.lastIndexOf("]");
  if (start < 0 || end < 0) {
    throw new Error("could not find array literal in new-logo.js");
  }
  const block = source.slice(start + 1, end);
  // Each line is `"..." ,` — match double-quoted strings (no escape handling
  // needed because the source has no backslashes inside).
  const lines: string[] = [];
  let i = 0;
  while (i < block.length) {
    if (block[i] !== '"') {
      i++;
      continue;
    }
    const j = block.indexOf('"', i + 1);
    if (j < 0) break;
    lines.push(block.slice(i + 1, j));
    i = j + 1;
  }
  return lines;
}

function rgbToHex([r, g, b]: [number, number, number]): string {
  const c = (n: number) =>
    Math.max(0, Math.min(255, Math.round(n)))
      .toString(16)
      .padStart(2, "0");
  return `#${c(r)}${c(g)}${c(b)}`;
}

function emit(rows: Cell[][]): string {
  const lines: string[] = [];
  lines.push(
    "/**",
    " * Auto-generated by `dev/gen-logo-data.ts` from `new-logo.js`.",
    " * Do NOT edit by hand — re-run the generator when the source updates.",
    " *",
    " * Cell-per-character logo data. Each cell carries the character glyph",
    " * (`█` / `░` / space) plus the RGB colour from the source ANSI art.",
    " */",
    "",
    "export type LogoCell = { ch: string; fg: string | null };",
    "",
    "export const LOGO_CELLS: readonly (readonly LogoCell[])[] = [",
  );
  for (const row of rows) {
    const cells = row
      .map((c) => {
        const ch = JSON.stringify(c.ch);
        const fg = c.rgb ? `"${rgbToHex(c.rgb)}"` : "null";
        return `{ch:${ch},fg:${fg}}`;
      })
      .join(",");
    lines.push(`  [${cells}],`);
  }
  lines.push("];", "");
  lines.push(`export const LOGO_WIDTH = ${rows[0]?.length ?? 0};`);
  lines.push(`export const LOGO_HEIGHT = ${rows.length};`);
  lines.push("");
  return lines.join("\n");
}

const source = readFileSync(SRC, "utf8");
const ansiLines = extractArray(source);
const rows = ansiLines.map(parseLine);

// Pad rows to the widest width so renderer never needs to bounds-check.
const widest = rows.reduce((n, r) => Math.max(n, r.length), 0);
for (const row of rows) {
  while (row.length < widest) row.push({ ch: " ", rgb: null });
}

writeFileSync(OUT, emit(rows));
console.log(`Wrote ${rows.length} rows × ${widest} cells → ${OUT}`);
