/**
 * LabelLens wordmark data. Source of truth lives in
 * `src/render/chrome/logo-data.ts` (auto-generated by
 * `scripts/gen-logo-data.ts` from `new-logo.js`).
 *
 * Two scales:
 *   FULL — 15 rows × 51 cells, per-cell cyan gradient. Splash + wide
 *          terminals.
 *   HALF — every other column dropped. ~26 cells wide. Letter shapes
 *          stay legible because block strokes survive. Sidebar fitting
 *          (24-32ch).
 */

import { LOGO_CELLS, LOGO_HEIGHT, LOGO_WIDTH, type LogoCell } from "./logo-data.ts";

export type { LogoCell };

export const LOGO_CELLS_FULL: readonly (readonly LogoCell[])[] = LOGO_CELLS;
export const LOGO_FULL_WIDTH = LOGO_WIDTH;
export const LOGO_FULL_HEIGHT = LOGO_HEIGHT;

function halveColumns(rows: readonly (readonly LogoCell[])[]): readonly (readonly LogoCell[])[] {
  return rows.map((row) => {
    const out: LogoCell[] = [];
    for (let i = 0; i < row.length; i += 2) {
      const cell = row[i];
      if (cell) out.push(cell);
    }
    return out;
  });
}

export const LOGO_CELLS_HALF: readonly (readonly LogoCell[])[] = halveColumns(LOGO_CELLS);
export const LOGO_HALF_WIDTH = LOGO_CELLS_HALF[0]?.length ?? 0;
export const LOGO_HALF_HEIGHT = LOGO_CELLS_HALF.length;
